[gcp_service_account]
type = "service_account"
project_id = "embodied-ritual-app"
private_key_id = "f331928123c98b44a806721bea37a3e4992d5692"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCSA4brfHE1tr2Y
xLvhOGR12EiyGQMYOcsRrTtDGSiBhX8L1uOC4a/v+5+RG46cML1oL7zoQpoAiru0
KvOihYT2jZMtxsys/IXB2x8aAyoTRSsb7AcQNFXrgnaeyNTRrEox3WcuUq9nBs1X
atuHMZGtyFlqhjWTm9A5mbrR9fEoTAY4vpsOjMgR/aVx++317PNm2hgbcgTCht7L
oHvnsP5yIw6c1/m7b98a1BZyO/GeUagqyX+F57wgrirZm7tb/ddyFlcvy6y0LH6/
jbOG1BTphve4tOqIEl1/gqT5LnVSf0IpKmNQ7KpHbIC4NOyBgIP2M/X+SqtBe+EK
G5f9rgIdAgMBAAECggEABGhbg/OfYz9fR85LMZ2cgruDA5qiWkfcVm3unQmUYcc1
h5ZMCzZkM5AFSBcXM1B8AeTMWg0wourihv9zl/4EfoDVkYsvwIUQRe18adzwlzZT
pSXMgh5iUu1URq90pS5YlbAY85qxYCB3cGJxurSyBhdHLmJbbwJEGIkId7AUleJx
8ZqSaaULnx7kB8KtYaAfEOfqveFKrJKC0hKonpHmcT74PgWCb/UFI9WrC8eINBrA
oTeVukPR20a3WVooc7Munc0DqJHuBu0iPNlx7h33OAo2TwyNRNCYcmKJfwp5LggR
yVfx4DWcWgWGrESTKJfiDH/LH4iGR0JyKC5qbvqTzQKBgQDG3V2o54RYU7ou8EXt
h7rbku4ALiYC7WrkQlZT/4V/mRgtHKgnyiJBH7UxhsEeKsWGdT34Y4efWSSJrHjj
qxHNYW4IctoPfNJoDi6TZ78kuFI7YLOL9SyMFBZdqJooM7QOFn98X4An5m+mGeSQ
u6WwNVuglvtMPIlZDouUaUxtpwKBgQC79vBzT4UEGj695Tc2cChtiA1EFEkhud4o
9Yl5JEZHtCcdEeHcXR88TSSlf4bn24yN5J6ZqH6MnQUKizBTX+CndotkOruIfMbZ
61du2rpbSwfUz2AB3+jNtm9bQQ4VPVfuDmOSxM20KO3tEDLXwt+ILSG1zwy14Duh
6Ukx2rsymwKBgHci2x97Q6Ae2OWR8HKy49Dznz3gZ8lNLsJ8s3czF2kv8HnmNx9P
S2I0erqm/j7yZM9+oZeTGQbvwqHv/6R1Mf8WpXLOS7EHmI3aITER8EMxYaJM9oOc
aAmrZxLJFUGMaAwgklOSaxZ8SNr7nCDRKhv8e14j1X0Ar0/5FMneo3j1AoGAa0tg
olIIGflpSzimtbp8OVnqSKxTup7AxBy05qPgQloB4cQta370r5VRj+8l8QAQUYbp
Sck2w8l18TjW0yDtumoe0437MsQXNpnyhOLycd54j+/4W9mWqKa1FiAii9lCci9g
g4035tleR25xt1wUAUXR8lhIZyGiqJ/kGkNDjHUCgYAstOwgjlwIyc+jok7cZf6o
L2GswDo7rAWE+d45i3USl2BD5dvT9UYbV2v0bS4kGI2kEIrAiG5iy6Sbu3RvWF2i
9QWsdKVl4e7GV+ZEra6/lDZRxyJbuggih1KFnrmSC2MKJzPs5cvYD1gApb5IIfzx
8ujH4aPIySN0JjRh9fCbzQ==
-----END PRIVATE KEY-----"""
client_email = "ritual-app-bot@embodied-ritual-app.iam.gserviceaccount.com"
client_id = "100375673318765108930"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ritual-app-bot%40embodied-ritual-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
